data:
  # train_files: /mnt/petrelfs/share_data/songmingyang/data/vl_reasoning/tool_dataset/toolrl_v1_gemmareachqa@train
  # val_files: /mnt/petrelfs/share_data/songmingyang/data/vl_reasoning/tool_dataset/toolrl_v1_gemmareachqa@validation
  train_files: /mnt/petrelfs/sunhaoyu/visual-code/datasets/tool_rlset_v1@train
  val_files: /mnt/petrelfs/sunhaoyu/visual-code/datasets/tool_rlset_v1@validation
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 32678
  max_response_length: 2048
  rollout_batch_size: 128
  # rollout_batch_size: 256
  val_batch_size: 1024
  format_prompt: /mnt/petrelfs/sunhaoyu/visual-code/EasyR1/examples/format_prompt/tool.jinja
  override_chat_template: null
  shuffle: true
  seed: 42
  max_pixels: 4194304
  min_pixels: 262144
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2

worker:
  actor:
    global_batch_size: 128
    micro_batch_size_per_device_for_update: 4
    micro_batch_size_per_device_for_experience: 16
    max_grad_norm: 1.0
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 6
    temperature: 1.0
    ###
    conversation_log_name: ray_test
    top_p: 0.99
    gpu_memory_utilization: 0.8
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 1
    limit_images: 0
    use_tool: true
    max_model_len: 128000
    max_multi_round_sequence_length: 35536
    val_override_config:
      temperature: 0.5
      n: 1
    tool_controller_addr: http://SH-IDC1-10-140-37-6:21112
    # tool_controller_addr: http://SH-IDC1-10-140-37-4:30001

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: tool_batch
    # reward_function: /mnt/petrelfs/songmingyang/code/reasoning/EasyR1/scripts/reward_function/tool_full_model_outputs.py:compute_score
    reward_function: /mnt/petrelfs/sunhaoyu/visual-code/EasyR1/examples/reward_function/tool.py:compute_score

trainer:
  total_epochs: 10
  max_steps: null
  project_name: easy_r1
  ###
  experiment_name: ray_test
  logger: ["console", "wandb"]
  nnodes: 1
  ###
  n_gpus_per_node: 4
  val_freq: 5  # -1 to disable
  val_before_train: false
  val_only: false
  val_generations_to_log: 3
  save_freq: 1  # -1 to disable
  save_limit: 2  # -1 to disable
  # 如果要从断点继续训练，则设置save_checkpoint_path为断点路径
  # save_checkpoint_path: "你的保存路径"  # 例如 "checkpoints/easy_r1/qwen2_5_3b_tool_grpo"
  # load_checkpoint_path: "你的检查点路径"  # 例如 "checkpoints/easy_r1/qwen2_5_3b_tool_grpo/global_step_100"
  # 检查点路径格式必须是 global_step_* 的形式，这在 ray_trainer.py 的 _load_checkpoint 函数中有明确要求
  ###
  save_checkpoint_path: /mnt/petrelfs/sunhaoyu/visual-code/EasyR1/checkpoints/checkpoints_ray_test
  load_checkpoint_path: null